### ISSUE TITLE
package.json script

### ISSUE THREAD

**Issue by stephanie56** [gonzalovazquez/react-redux-scaffolding#6]
The script below doesn't work with windows system and will cause an error when running `npm install` :)

```
"scripts": {
    "dist": "NODE_ENV=production webpack --progress"
}
```

For windows user this issue can be fixed with: 
```
"scripts": {
    "dist": "SET NODE_ENV=production webpack --progress"
}
```

[reference](http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows)

**Comment by gonzalovazquez** [comment]
Thanks for the issue!

I have addressed it with the cross-env package:

https://github.com/gonzalovazquez/react-redux-scaffolding/blob/v1/production-ready/package.json#L21

👍
